# Generated by Django 2.1.5 on 2020-04-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apid', models.CharField(max_length=20)),
                ('apname', models.CharField(max_length=100)),
                ('apcity', models.CharField(max_length=100)),
                ('apcountry', models.CharField(max_length=100)),
                ('apIATA', models.CharField(max_length=100)),
                ('apICAO', models.CharField(max_length=100)),
                ('aptimezone', models.TimeField(max_length=100)),
                ('aptype', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
    ]
