# Generated by Django 2.1.5 on 2020-04-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadharCard_no', models.CharField(max_length=20)),
                ('passport_no', models.CharField(max_length=100)),
                ('ticket_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
