# Generated by Django 2.1.5 on 2020-04-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_no', models.CharField(max_length=100)),
                ('tno', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Checkin',
            },
        ),
        migrations.CreateModel(
            name='Domestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=20)),
                ('alname', models.CharField(max_length=100)),
                ('from_ap', models.CharField(max_length=100)),
                ('to_ap', models.CharField(max_length=100)),
                ('no_of_flights', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('flight_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'domestic',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('aadharCard_no', models.CharField(max_length=20)),
                ('passport_no', models.CharField(max_length=100)),
                ('al_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ap', models.CharField(max_length=100)),
                ('from_ap_id', models.CharField(max_length=100)),
                ('to_ap', models.CharField(max_length=100)),
                ('to_ap_id', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=100)),
                ('departs', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('al_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='International',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(max_length=20)),
                ('alname', models.CharField(max_length=100)),
                ('from_ap', models.CharField(max_length=100)),
                ('to_ap', models.CharField(max_length=100)),
                ('no_of_flights', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('flight_time', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'international',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('no_of_luggages', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'passenger',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_ap', models.CharField(max_length=100)),
                ('from_ap_id', models.CharField(max_length=100)),
                ('to_ap', models.CharField(max_length=100)),
                ('to_ap_id', models.CharField(max_length=100)),
                ('departs', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.AlterField(
            model_name='airline',
            name='apstate',
            field=models.CharField(max_length=100),
        ),
    ]
